{% set name = "mir-flare" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e07381b5d3c64eaa666bb9177105af4d4b345e3470ed2d44e7f0a2b0308421af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - ipython
    - memory_profiler
    - nbsphinx
    - nptyping
    - numba
    - numpy >=1.16.0
    - pymatgen
    - pytest >=4.6
    - python >=3.6
    - scipy

test:
  imports:
    - flare
    - flare.ase
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mir-group/flare
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source Python package for creating fast and accurate atomistic potentials.

  description: |
    FLARE is an open-source Python package for creating fast and accurate 
    atomistic potentials.
  doc_url: https://flare.readthedocs.io/
  dev_url: https://github.com/mir-group/flare

extra:
  recipe-maintainers:
    - jan-janssen
