{% set name = "mir-flare" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f15273d9ef85d05be9c558b316ba58536ba8fe3968c21e8a5a610573a35eece3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ase
    - ipython
    - memory_profiler
    - nbsphinx
    - nptyping
    - numba
    - numpy <=1.20.0
    - pymatgen <2021
    - pytest >=4.6
    - python >=3.6
    - scipy
    - pytest-mock

test:
  imports:
    - flare
    - flare.ase
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mir-group/flare
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source Python package for creating fast and accurate atomistic potentials.

  description: |
    FLARE is an open-source Python package for creating fast and accurate 
    atomistic potentials.
  doc_url: https://flare.readthedocs.io/
  dev_url: https://github.com/mir-group/flare

extra:
  recipe-maintainers:
    - jan-janssen
