{% set name = "mir-flare" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mir-group/flare/archive/refs/tags/{{ version }}.tar.gz
  sha256: e377ec63200e3099af5fd1607bbbd22abe855db0fd13d565f6278289da785985

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py>39]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - cmake
    - liblapacke
    - eigen
  run:
    - ase
    - ipython
    - memory_profiler
    - jupyter
    - nbconvert
    - pyyaml
    - docutils =0.17.1
    - alabaster =0.7.12
    - babel
    - pygments =2.11.2
    - nbsphinx
    - nptyping
    - numba
    - numpy <=1.20.3
    - pytest >=4.6
    - python
    - scipy
    - pytest-mock

test:
  imports:
    - flare
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mir-group/flare
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source Python package for creating fast and accurate atomistic potentials.

  description: |
    FLARE is an open-source Python package for creating fast and accurate 
    atomistic potentials.
  doc_url: https://flare.readthedocs.io/
  dev_url: https://github.com/mir-group/flare

extra:
  recipe-maintainers:
    - YuuuXie
    - jan-janssen
