{% set name = "mir-flare" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mir-group/flare.git
  git_tag: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - flare-otf = flare.scripts.otf_train:main

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >=3.6
    - mkl-devel
    - mkl-service
    - mkl_fft
    - openmp
    - setuptools
  run:
    - ase
    - numba
    - numpy
    - python >=3.6
    - pyyaml
    - scipy

test:
  imports:
    - flare
    - flare.bffs.sgp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mir-group/flare
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An open-source Python package for creating fast and accurate atomistic potentials.

  description: |
    FLARE is an open-source Python package for creating fast and accurate 
    atomistic potentials.
  doc_url: https://mir-group.github.io/flare/
  dev_url: https://github.com/mir-group/flare

extra:
  recipe-maintainers:
    - YuuuXie
    - jan-janssen
